### ISSUE TITLE
단위에 맞게 데이터값 변경

### ISSUE THREAD

**Issue by beforesol** [beforesol/alcohol-diary#29]
단위나 음주량 변화하면 store 업데이트 및 DB 업데이트

### 단위 데이터 생성
- 단위는 ml 기준으로 한다.
- 단위는 기본값이 존재하고, 사용자가 설정탭에서 수정할 수 있다.
- 단위값은 users -> units에 저장된다.

### TODO
- [x] 단위 기본값 생성(id, ml)
- [x] 사용자가 단위를 바꾸면 users의 units 값에 따라 화면 업데이트

### 이슈
- [x] 오른쪽 버튼은 firebase 데이터에 의존하는데, 단위가 바뀌면 firebase가 바껴도 종종 화면이 업데이트가 되지 않음 -> 오른쪽 버튼도 스토어 값에 의존해서 변경하기
